=== Jedrzejalicki/Web_page/index.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="formula1">
		<xs:complexType>
		<xs:sequence>
			<xs:element name="author">
				<xs:complexType>
					<xs:all>
						<xs:element  name="name" type="shortStringType" />
						<xs:element  name="surname" type="shortStringType"/>
						<xs:element name="group" type="xs:integer" />
						<xs:element name="phone" type="phoneNumberType"/>
					</xs:all>
				</xs:complexType>
			</xs:element>
			<xs:element name="drivers" type="driversType"/>
			<xs:element ref="facts" minOccurs="0" maxOccurs="3"/>
			<xs:element name="links" type="linksType"/>
			<xs:element name="forms">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="formGroup"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="teams" type="teamsType"/>
			
			
		</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="shortStringType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="longStringType">
		<xs:restriction base="xs:string">
			<xs:minLength value="100"/>
			<xs:maxLength value="9000"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="driversType">
		<xs:sequence>
			<xs:element name="driver" maxOccurs="22" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="shortStringType">
							<xs:attribute type="numberType" name="id_number" />
							<xs:attribute type="numberType" name="podiums"/>
							<xs:attribute ref="team"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="numberType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="200"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="facts" type="factsType"/>
	<xs:complexType name="factsType">
		<xs:sequence>
			<xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="kind" type="kindType" use="required"/>
		<xs:attribute name="current" use="optional" default="no">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="yes|no"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="componentType">
		<xs:choice>
			<xs:element name="text" type="textType"/>
			<xs:element ref="text1"/>
			<xs:element name="rule" type="shortStringType" minOccurs="0" maxOccurs="unbounded" />
		</xs:choice>
	</xs:complexType>


	<xs:element name ="text1" type="longStringType"/>

	<xs:simpleType name="kindType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="car"/>
			<xs:enumeration value="rules"/>
			<xs:enumeration value="informations"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="textType" mixed="true">
		<xs:choice>
			<xs:element name="history">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="firstRace" type="xs:string"/>
						<xs:element ref="text1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:simpleType name="union1Type">
		<xs:union memberTypes="xs:decimal xs:string"/>
	</xs:simpleType>

	<xs:complexType name="linksType">
		<xs:sequence>
			<xs:element name="link" type="linkType" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
		</xs:complexType>


		<xs:complexType name="linkType">
			<xs:simpleContent>
				<xs:extension base="shortStringType">
					<xs:attribute type="shortStringType" name="source"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>

	
	<xs:attribute name="team">
		<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Williams"/>
			<xs:enumeration value="Mercedes"/>
			<xs:enumeration value="Ferrari"/>
			<xs:enumeration value="RedBull"/>
			<xs:enumeration value="Mclaren"/>
			<xs:enumeration value="AlfaRomeo"/>
			<xs:enumeration value="AlphaTauri"/>
			<xs:enumeration value="Rentaul"/>
			<xs:enumeration value="Haas"/>
			<xs:enumeration value="RacingPoint"/>
		</xs:restriction>
	</xs:simpleType>
	</xs:attribute>

	<xs:simpleType name="unionType">
		<xs:union memberTypes="shortStringType longStringType"></xs:union>
	</xs:simpleType>
	
	<xs:group name="formGroup">
		<xs:sequence>
			<xs:element name="bigEntry" type="unionType"/>
			<xs:element name="entry" type="shortStringType" maxOccurs="3" minOccurs="0"/>
			<xs:element name="choice" type="choiceType"/>
			<xs:element name="list"  type="optionList"/>
			<xs:element name="favouriteTeam" type="favouriteTeamType"/>
		</xs:sequence>
	</xs:group>

	<xs:simpleType name="phoneNumberType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}"/>
			</xs:restriction>
			</xs:simpleType>

	<xs:complexType name="choiceType">
		<xs:sequence>
			<xs:element name="gender1" type="xs:string"/>
			<xs:element name="gender2" type="xs:string"/>
			<xs:element name="gender3" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

		<xs:complexType name="favouriteTeamType">
			<xs:sequence>
				<xs:element name="listOption" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="shortStringType">
								<xs:attribute ref="team"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>

	
	<xs:complexType name="teamsType">
		<xs:sequence>
			<xs:element name="team" maxOccurs="10" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
					<xs:element name="image">
						<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="shortStringType">
							<xs:attribute name="source" type="xs:anyURI"/>
						</xs:extension>
					</xs:simpleContent>
						</xs:complexType>
					</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>


	<xs:simpleType name="optionList">
		<xs:restriction>
			<xs:simpleType>
				<xs:list>
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:list>
			</xs:simpleType>
			<xs:length value="5" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Jedrzejalicki/Web_page/index.xml
<?xml version="1.0"  encoding="UTF-8"?>

    <formula1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="index.xsd">
	
	 <author>
		<name>Jedrzej</name>
		<surname>Alicki</surname>
		<group>2</group>
		 <phone>000-000-000</phone>
   </author>
	
	<drivers>
		<driver id_number="63" podiums="000" team="Williams">Gorge Russel</driver>
		<driver id_number="88" podiums="000" team="Williams">Nicholas Latifi</driver>
		<driver id_number="20" podiums="001" team="Haas">Kevin Magnusen</driver>
		<driver id_number="08" podiums="010" team="Haas">Romain Grosjean</driver>
		<driver id_number="07" podiums="103" team="AlfaRomeo">Kimi Raikonen</driver>
		<driver id_number="99" podiums="000" team="AlfaRomeo">Antonio Govinazzi</driver>
		<driver id_number="11" podiums="009" team="RacingPoint">Sergio Perez</driver>
		<driver id_number="18" podiums="002" team="RacingPoint">Lance Stroll</driver>
		<driver id_number="10" podiums="002" team="AlphaTauri">Piere Gasly</driver>
		<driver id_number="26" podiums="003" team="AlphaTauri">Danil Kvyat</driver>
		<driver id_number="05" podiums="121" team="Ferrari">Sebastian Vettel</driver>
		<driver id_number="16" podiums="012" team="Ferrari">Charles Leclerc</driver>
		<driver id_number="27" podiums="000" team="Rentaul">Esteban Ocon</driver>
		<driver id_number="03" podiums="031" team="Rentaul">Daniel Ricardo</driver>
		<driver id_number="23" podiums="001" team="RedBull">Alex Albon</driver>
		<driver id_number="33" podiums="040" team="RedBull">Max Verstappen</driver>
		<driver id_number="04" podiums="001" team="Mclaren">LandoNorris</driver>
		<driver id_number="55" podiums="002" team="Mclaren">Carlos Sainz</driver>
		<driver id_number="77" podiums="055" team="Mercedes">Valtteri Bottas</driver>
		<driver id_number="44" podiums="163" team="Mercedes">Lewis Hamilton</driver>
	</drivers>

		<facts kind="informations" current="no">
			<component>
				<text>
				<history>		
					<firstRace>First race took place in Turin in Italy in 1946</firstRace>
						<text1>
							The Formula One series originated with the European Championship of Grand Prix motor racing (q.v. for pre-1947 history) of the 1920s and 1930s. 
							The formula comprises a set of rules that all participants' cars must meet. Formula One was a new formula agreed upon during 1946 after World War II, 
							with the first non-championship races taking place that year. The first Formula 1 race was the1946 Turin Grand Prix.
							 A number of Grand Prix racing organisations had laid out rules
							for a world championship before the war, but due to the suspension of racing during the conflict, the World Drivers' Championship did not become formalised until 1947. 
							The first world championship race took place at Silverstone in the United Kingdom in 1950. A championship for constructors followed in 1958.
							National championships existed in South Africa and the UK in the 1960s and 1970s. Non-championship Formula One events were held[by whom?] for many years, 
							but due to the increasing cost of competition, the last of these occurred in 1983.[ On 26 November 2017 Formula One unveiled its new logo, 
							following the 2017 season finale in Abu Dhabi during the Abu Dhabi Grand Prix at Yas Marina Circuit. The new logo replaced F1's iconic "flying one", 
							which had been the sport's trademark since 1993.
							</text1>
						</history>
				</text>
			</component>
		</facts>
	
		<facts kind="rules" current="yes">
		<component>
			<rule>The “One Move” Defending Rule</rule>
			<rule>Drivers Must Qualify Within 107% Of The Pole-Sitter</rule>
			<rule>If an engine part is changed, they take a grid drop penalty</rule>
			<rule>Speeding In The Pitlane? You Get A Penalty</rule>
			<rule>They Must Change Tyre Compounds In The Race</rule>
			<rule>Safety Car Line Overtaking</rule>
			<rule>Rain Lights MUST Be Used In The Wet</rule>
		</component>
		</facts>
		
		<facts kind="car" current="yes">
		<component>
				<text1>
					A Formula One car is a single-seat, open cockpit, open-wheel racing car with substantial front and rear wings,
					and an engine positioned behind the driver, intended to be used in competition at Formula One racing events. 
					The regulations governing the cars are unique to the championship and specify that cars must be constructed by the racing teams themselves,
					though the design and manufacture can be outsourced.
					Modern-day Formula One cars are constructed from composites of carbon fibre and similar ultra-lightweight materials.
					The minimum weight permissible is 740 kg (1,631 lb) including the driver but not fuel. Cars are weighed with dry-weather tyres fitted. 
					Prior to the 2014 F1 season, cars often weighed in under this limit so teams added ballast in order to add weight to the car.
					The advantage of using ballast is that it can be placed anywhere in the car to provide ideal weight distribution.
					This can help lower the car's centre of gravity to improve stability and also allows the team to fine-tune the weight distribution 
					of the car to suit individual circuits. 
				</text1>
			</component>
		</facts>

		<links>
			<link source="https://www.formula1.com/en/results.html/2020/drivers.html">Driver Standings</link>
			<link source="https://en.wikipedia.org/wiki/Formula_One_regulations">Regulations</link>
			<link source="https://www.formula1.com/en.html">Official webpage</link>
			<link source="https://www.tutorialspoint.com/formula_one/formula_one_quick_guide.htm">quick guide</link>
			<link source="https://en.wikipedia.org/wiki/2020_Formula_One_World_Championship">Informations</link>
			<link source="https://www.hotcars.com/15-rules-every-formula-one-driver-has-to-follow/">15 rules</link>
		</links>
		
		<forms>
			<bigEntry>Why you love motorsports</bigEntry>
			<entry>First name</entry>
			<entry>Last name</entry>
			<entry>Password</entry>
			
			<choice>
				<gender1>Men</gender1>
				<gender2>Female</gender2>
				<gender3>I don't want to answer</gender3>
			</choice>
			
			<list>F1 MotoGP NASCAR Raylling Speedway</list>
				
					
					
					
					
			
			
		<favouriteTeam>
			<listOption team="Mercedes" >Mercedes</listOption>
			<listOption team="Ferrari">Ferrari</listOption>
			<listOption team="RedBull">Red Bull</listOption>
			<listOption team="Mclaren">McLaren</listOption>
			<listOption team="Rentaul">Rentaul</listOption>
			<listOption team="AlphaTauri">Alpha Tauri</listOption>
			<listOption team="RacingPoint">Racing Point</listOption>
			<listOption team="AlfaRomeo">Alfa Romeo</listOption>
			<listOption team="Haas">Haas</listOption>
			<listOption team="Williams">Williams</listOption>
		</favouriteTeam>
		
		</forms>

		<teams>
			<team><image source="Williams.jpg">Williams</image></team>
			<team><image source="AlfaRomeo.jpg">Alfa Romeo</image></team>
			<team><image source="RacingPoint.jpg">Racing Point</image></team>
			<team><image source="Mercedes.jpg">Mercedes</image></team>
			<team><image source="Ferrari.jpg">Ferrari</image></team>
			<team><image source="RedBull.jpg">Red Bull</image></team>
			<team><image source="Rentaul.jpg">Rentaul</image></team>
			<team><image source="McLaren.jpg">McLaren</image></team>
			<team><image source="AlphaTauri.jpg">Alpha Tauri</image></team>
		</teams>
		</formula1>
